services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    tty: true
    stdin_open: true
    ports:
        - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command:
      - start-dev
    depends_on:
      - postgres-kc

  postgres-kc:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    tty: true
    restart: always
